### ISSUE TITLE
.gitignore no longer uses the Git icon

### ISSUE THREAD

**Issue by michaelblyons** [ihodev/sublime-file-icons#60]
I think this is a regression: The orange "Git" logo used to appear for the `.gitignore` files, but with a recent update it no longer does.

It is possible that this behaviour is intended when there is no Git syntax package installed (or the behaviour was provided through my theme, rather than this package), but looking at the [`icons.json`][icons.json] file, it sort of looks like a default override is expected.

#### Expected Behavior
[Files named `.gitignore`][icons.json] use the Git logo in the left sidebar.

#### Current Behavior
Left sidebar file named `.gitignore` has a generic "rectangle with folded corner" icon.

#### Steps to Reproduce (for bugs)

1. Open Folder (folder contains a `.gitignore` file)
2. Look at the icon in the left sidebar.

#### Your Environment
- Windows Server 2008
- Possibly relevant installed packages:
    + GitGutter
    + Boxy Theme
    + No syntax package that targets `.gitignore` is installed. The scope of the file is `text.plain`.

Output of Environment:

- File Icons: 2.2.0
- Sublime Text: 3126
- Platform: windows
- Package Control: True
- Current Theme: `Boxy Ocean.sublime-theme`
- Installed Themes: `{'Boxy Theme': ['Boxy Monokai.sublime-theme', 'Boxy Nova.sublime-theme', 'Boxy Ocean.sublime-theme', 'Boxy Solarized Dark.sublime-theme', 'Boxy Solarized Light.sublime-theme', 'Boxy Tomorrow.sublime-theme', 'Boxy Yesterday.sublime-theme'], 'Theme - Default': ['Default.sublime-theme']}`

[icons.json]: https://github.com/ihodev/sublime-file-icons/blob/dev/src/icons.json#L357

**Comment by ihodev** [comment]
@michaelblyons It works like a charm for me. I think that you disabled `Shell Script (Bash)` syntax from what  `git` syntax aliase inherited to.

**Comment by michaelblyons** [comment]
Weird. It is working now after a second close/re-open cycle of ST3. I do not know what went wrong the first time.
