### ISSUE TITLE
Gulp/Grunt Icon

### ISSUE THREAD

**Issue by MandarSant** [ihodev/sublime-file-icons#61]
Icon for gulp and grunt

**Comment by ihodev** [comment]
This package adds them by default. Provide more details if you have some problems.

**Comment by MandarSant** [comment]
@ihodev it shows js icon

**Comment by ihodev** [comment]
@MandarSant Please provide:

1. Output from `File Icons: Environment` command (you find it in Command Palette)
2. Console output via menu item `View -> Show Console`
3. Your user settings `Preferences -> Package Settings -> File Icons -> Settings - User `
