### ISSUE TITLE
why not support Jade & JSX & pug ?

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [ihodev/sublime-file-icons#62]
why not support Jade & JSX & pug ?
![files-icons-error](https://cloud.githubusercontent.com/assets/18028768/20755401/cf8c82e2-b749-11e6-94f7-6684c4d899be.png)

VS code:
![vs-icons](https://cloud.githubusercontent.com/assets/18028768/20755534/49afccc8-b74a-11e6-9768-52808ae4459c.png)
Atom:
![atom-icons](https://cloud.githubusercontent.com/assets/18028768/20755722/f21f2d72-b74a-11e6-9051-26c222a0619f.png)

**Comment by r3nya** [comment]
Hey!

Please install https://github.com/babel/babel-sublime and https://packagecontrol.io/packages/Jade ;)

**Comment by xgqfrms-GitHub** [comment]
I had been installed jade & babel!
it does work at all!
you icons is not include jade.svg & jsx.svg!

maybe I should try this!

https://github.com/ufo-github/SetiUI-Icons-Sublime

**Comment by ihodev** [comment]
You have to install 'zz File Icons' to see the right icons.

**Comment by xgqfrms-GitHub** [comment]
I have to say good bye!

**Comment by r3nya** [comment]
@xgqfrms-GitHub gl hf no bs!

**Comment by xgqfrms-GitHub** [comment]
gl hf no bs - good luck, have fun, no backstabs!
http://www.urbandictionary.com/define.php?term=gl

**Comment by r3nya** [comment]
@xgqfrms-GitHub so what?
