### ISSUE TITLE
Automatically update SublimeLinter settings

### ISSUE THREAD

**Issue by systematicat** [ihodev/sublime-file-icons#65]
Hi! Thank you for your awesome work! 
I have a stupid question about syntax aliases https://github.com/ihodev/sublime-file-icons#sublime-linter-setup 
When should I edit them in the Linter's config? 
Only when I use proper lint plugin or I can add them all (aliases) right after installing zz File Icon? 
Thanx!

**Comment by ihodev** [comment]
Hi! 

> Only when I use proper lint plugin or I can add them all (aliases) right after installing zz File Icon?

As you want, I left this note in case if you'll be surprised that e.g. JSON linter doesn't work for your `package.json` or `.eslintrc.json` files. I think I'll automate settings update in the next release, so there is no need to add them manually.

**Comment by systematicat** [comment]
Thank you @ihodev! 
It would be gr8! Automated settings update is a must for such forgetfull person like me.
